/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package t3bmodtabla;

import java.awt.Point;
import java.util.ArrayList;
import java.util.HashMap;
import t3bmodtabla.gui.T3BTabla;

/**
 *
 * @author daniel
 */
public class Ventana1 extends javax.swing.JFrame {
    
    T3BTabla tbl1 = null;
    HashMap<String, String> cnf = null;
    ArrayList<String> cols = null;

    /**
     * Creates new form Ventana1
     */
    public Ventana1() {
        initComponents();
        
//        cols = new ArrayList();
//        cols.add("tclave_Region_50_s");
//        cols.add("fecha_Fecha_100_h");
//        cols.add("valorInv01_Valor Inventario_120_d");
//        cols.add("valorVentaMPcosto_Valor Venta MP_120_d");
//        cols.add("valorVentaMCcosto_Valor Venta MC_120_d");
        cnf = new HashMap();
        cnf.put("dbHost","100.14.0.26");
        cnf.put("dbUser","dba");
        cnf.put("dbPass","5575349");
        cnf.put("dbPort","2638");
        cnf.put("dbName","master64");
        cnf.put("dbClassDriver","com.sybase.jdbc4.jdbc.SybDriver");
        cnf.put("dbUrl","jdbc:sybase:Tds:");
        tbl1 = new T3BTabla(" select tclave as \"Almacen\", fecha as \"Fecha\", isnull(valorInv01,0) as \"Valor Inventario Diario\", isnull(valorVentaMPcosto,0) as \"Valor Venta MP a Costo\", isnull(valorVentaMCcosto,0) as \"Valor Venta MC a Costo\" from MCA_TANALISISCONTROLINVENTARIO where tclave = '1000' and fecha >= '2016-01-01' ", cols, cnf, true);
        tbl1.setVisible(true);
        this.pnl1.removeAll();
        this.pnl1.add(tbl1);
        this.setSize(500, 500);
        this.setLocation(10,10);
        this.setTitle("Hola");
        creaEventoTabla();
    }
    
    private void creaEventoTabla(){
        try{
            this.tbl1.getTabla().addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Point p = evt.getPoint();
                System.out.println(p.toString());
                int fila = tbl1.getTabla().rowAtPoint(p);
                int col  = tbl1.getTabla().columnAtPoint(p);
                System.out.println("Celda: " + tbl1.getValueAt(fila, col));
            }
        });
        }catch(Exception ex){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pnl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl1MouseClicked(evt);
            }
        });
        pnl1.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl1, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(pnl1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl1MouseClicked
        
    }//GEN-LAST:event_pnl1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnl1;
    // End of variables declaration//GEN-END:variables
}
